### ISSUE TITLE
Why is the transformation matrix between source and target point cloud a identity(eye) matrix?

### ISSUE THREAD

**Issue by EryiXie** [sayands/sgaligner#3]
Hello, I am a little bit confused about the ground truth transformation between the source and reference point clouds, by running the inference code with the default eye matrix as gt_transform, I can't reproduce the result given in the paper. Will there be an update to add the code for the exact generation method and margin thresholds of the gt_transform in the future?
Thank you very much.

https://github.com/sayands/sgaligner/blob/49ae3e1398e369557878af7c45252817a7abe72f/src/inference/sgaligner/inference_align_reg.py#L153C21-L153C62

**Comment by sayands** [comment]
The transformation matrix is an identity matrix because in our case, we use subscans generated from the parent scans in 3RScan and hence, they are already aligned as in their transformation matrix should be identity. Could you maybe describe your process about reproducing our results a bit more and direct me to which result you’re unable to reproduce? 

The values might vary a bit depending on the subscan generation process but should be reflective of our results in the paper.
